# Generated by Django 6.0.1 on 2026-01-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('platform', models.CharField(choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('LinkedIn', 'LinkedIn')], max_length=50)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Completed', 'Completed')], max_length=50)),
                ('budget', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
